---
- hosts: localhost
  vars:
    remote_user: vagrant
    #remote_user: ubuntu
    pvs: /dev/xvdb
  vars_files:
    - vars.yml
  sudo: yes
  user: root
  connection: local
  gather_facts: False
  roles:
  tasks:
  - name: Create a volume group on top of physical volume
    lvg:
      vg: vgdata
      pvs: "{{pvs}}"
  - name: lvcreate for /var
    lvol:
      vg: vgdata
      lv: varlv
      size: 2000M
      force: yes
  - name: create file system for /var
    filesystem: 
      fstype: ext4
      dev: /dev/vgdata/varlv
  - name: mount logical volume for /media/var
    mount: 
      name: /media/var
      src: /dev/vgdata/varlv
      fstype: ext4
      state: mounted
  - name: Synchronization of src to dest, ignore errors (this may happen is files are missing permissions) 
    synchronize: 
      src: /var/ 
      dest: /media/var
    ignore_errors: yes
  - name: create /old_var dir
    file:
      path: /old_var
      state: directory
  - name: rsync /var to /old_var
    synchronize:
      src: /var/
      dest: /old_var
    ignore_errors: yes
  - name: mount logical volume for /var
    mount:
      name: /var
      src: /dev/vgdata/varlv
      fstype: ext4
      state: mounted
  - name: lvcreate for /tmp
    lvol:
      vg: vgdata
      lv: tmplv
      size: 2000M
      force: yes
  - name: create file system for /tmp
    filesystem:
      fstype: ext4
      dev: /dev/vgdata/tmplv
  - name: mount logical volume for /tmp
    mount:
      name: /tmp
      src: /dev/vgdata/tmplv
      fstype: ext4
      state: mounted
  - name: set permissions for tmp so everybody can use it
    shell: chmod 1777 /tmp
  - name: lvcreate for /var/tmp
    lvol:
      vg: vgdata
      lv: vartmplv
      size: 1000M
      force: yes
  - name: create file system for tmp
    filesystem:
      fstype: ext4
      dev: /dev/vgdata/vartmplv
  - name: mount logical volume for tmp
    mount:
      name: /var/tmp
      src: /dev/vgdata/vartmplv
      fstype: ext4
      state: mounted
  - name: lvcreate for /var/log
    lvol:
      vg: vgdata
      lv: varloglv
      size: 1000M
      force: yes
  - name: create file system for /var/log
    filesystem:
      fstype: ext4
      dev: /dev/vgdata/varloglv
  - name: mount logical volume for /var/log
    mount:
      name: /var/log
      src: /dev/vgdata/varloglv
      fstype: ext4
      state: mounted
  - name: lvcreate for /var/log/audit
    lvol:
      vg: vgdata
      lv: varlogauditlv
      size: 1000M
      force: yes
  - name: create file system for /var/log/audit
    filesystem:
      fstype: ext4
      dev: /dev/vgdata/varlogauditlv
  - name: mount logical volume for /var/log/audit
    mount:
      name: /var/log/audit
      src: /dev/vgdata/varlogauditlv
      fstype: ext4
      state: mounted
  - name: lvcreate for /home
    lvol:
      vg: vgdata
      lv: homelv
      size: 2000M
      force: yes
  - name: create file system for /media/home
    filesystem:
      fstype: ext4
      dev: /dev/vgdata/homelv
  - name: mount logical volume for /media/home
    mount:
      name: /media/home
      src: /dev/vgdata/homelv
      fstype: ext4
      state: mounted
  - name: Synchronization of src to dest
    synchronize:
      src: /home/
      dest: /media/home
  - name: create /old_home dir
    file:
      path: /old_home
      state: directory
  - name: rsync /home to /old_home
    synchronize:
      src: /home/
      dest: /old_home
  - name: mount logical volume for /home
    mount:
      name: /home
      src: /dev/vgdata/homelv
      fstype: ext4
      state: mounted

