---
- hosts: localhost
  vars:
    remote_user: vagrant
    #remote_user: ubuntu
  vars_files:
    - vars.yml
  sudo: yes
  user: root
  connection: local
  gather_facts: False
  roles:
  tasks:
  - name: update apt cache
    apt: update_cache=yes
  - name: Install required system packages.
    apt: pkg={{ item }} state=installed 
    sudo_user: root
    with_items: 
      - "{{ system_packages }}"

